### ISSUE TITLE
PHP 8.3 compatibility

### ISSUE THREAD

**Issue by alfredbez** [spryker/docker-php#83]
Do you have any ETA on when an image with PHP 8.3 will be available? Is there any public status regarding the compatibility between PHP 8.3 and spryker modules?

I'm aware of [this page](https://docs.spryker.com/docs/scos/user/intro-to-spryker/whats-new/supported-versions-of-php.html#php-8), but it looks a bit off to me:

![image](https://github.com/spryker/docker-php/assets/1001186/b398f2d7-1260-4c85-8dd6-ae569516eecb)

The first sentence says, that support for 8.1 was added in November 2023, but PHP 8.2 has been supported already since December 2022. This is likely a typo, right?

**Comment by gechetspr** [comment]
Hey!
Thank you for reaching us.

We are planning to add support of PHP8.3 in Q3. Image will be provided after we ensure that all Spryker modules are compatible.

Regarding the text, it looks like a "typo". What we meant, that from November 2023 PHP8.1 is a minimal required version. Usually we add support of the next version at least 1 product release prior to dropping current minimal version

Since PHP versions now have extended security support life time, we need to make a decision if we will drop 8.1 this November.

Could I help you with something else?

**Comment by alfredbez** [comment]
Do you know if you already plan support for PHP 8.4? The release cycle for PHP version has been quite stable for the last couple of years I would say.

**Comment by gechetspr** [comment]
We have no such plan this year as I can see. Usually we try to stick with 2 versions in the same time.

**Comment by alfredbez** [comment]
It looks like you're supporting the version that is in security support + the older version of the two that have active support. Do you have any plans to change that to support both versions that have active support instead?

**Comment by gechetspr** [comment]
Not yet.
We don't want to force people to migrate to the newer version, while version is use is still in support, that's why we keep the minimal version that is in security support.
We will check if we can to include support of newer versions sooner, but we will not be possible to do it in Q3 for sure. So in Q3 we will add PHP8.3 support and will check when we can add PHP8.4 support.

**Comment by alexanderM91** [comment]
Hi, PHP 8.3 is available for use.

**Comment by alfredbez** [comment]
Hi @gechetspr, do you have any updates on this topic (PHP 8.4 support)?

**Comment by christianlerch** [comment]
Let's continue the discussion in the new issue I created: [Add support for PHP 8.4 #110
](https://github.com/spryker/docker-php/issues/110)
